config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories

  devise_for :users
  root to: 'home#index'
  get '/search', to: 'loos#search'
  get '/about', to: 'home#about'
  resources :loos
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  has_attached_file :file, :styles => { :medium => "600x600>", :small => "300x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :loos
end

app/models/loo.rb
class Loo < ActiveRecord::Base
  belongs_to :category
  has_many :attachments, as: :attachable
  accepts_nested_attributes_for :attachments

  validates :name, :location_name, presence: true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def self.search(terms, loo)
    if terms && loo
      where(
        "name like ? OR description like ? OR
        postal_code like ? OR
        locality like ? OR
        country like ? OR
        administrative_area_level_1 like ? OR
        formatted_address like ?",
        "%#{terms}%",
        "%#{terms}%",
        loo && loo[:postal_code] ? loo[:postal_code] : "",
        loo && loo[:locality] ? loo[:locality]: "",
        loo && loo[:country] ? loo[:country] : 0,
        loo && loo[:administrative_area_level_1] ? loo[:administrative_area_level_1] : "",
        loo && loo[:formatted_address] ? loo[:formatted_address] : "")
      .order("name ASC")
    elsif terms
      where( "name like ? OR description like ? OR formatted_address like ?", "%#{terms}%", "%#{terms}%", "%#{terms}%").order("name ASC")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  validates :firstname, :lastname, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def title
    @title ||= "TheLooProject"
  end
  helper_method :title

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :firstname
      devise_parameter_sanitizer.for(:sign_up) << :lastname
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @title = "About | TheLooProject"
  end
end

app/controllers/loos_controller.rb
class LoosController < ApplicationController
  before_action :set_loo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

  # GET /loos
  # GET /loos.json
  def index
    @title = "Listing loos | TheLooProject"
    @loos = Loo.all
  end

  def search
    if params[:q] || params[:loo]
      @loos = Loo.search(params[:q], params[:loo])
    else
      @loos = []
    end
    @title = params[:q] + " | TheLooProject"
    render :index
  end

  # GET /loos/1
  # GET /loos/1.json
  def show
  end

  # GET /loos/new
  def new
    @title = "Share loo location & Infor | TheLooProject"
    @loo = Loo.new
  end

  # GET /loos/1/edit
  def edit
  end

  # POST /loos
  # POST /loos.json
  def create
    @loo = Loo.new(loo_params)

    respond_to do |format|
      if @loo.save
        format.html { redirect_to @loo, notice: 'Loo was successfully created.' }
        format.json { render :show, status: :created, location: @loo }
      else
        format.html { render :new }
        format.json { render json: @loo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loos/1
  # PATCH/PUT /loos/1.json
  def update
    respond_to do |format|
      if @loo.update(loo_params)
        format.html { redirect_to @loo, notice: 'Loo was successfully updated.' }
        format.json { render :show, status: :ok, location: @loo }
      else
        format.html { render :edit }
        format.json { render json: @loo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loos/1
  # DELETE /loos/1.json
  def destroy
    @loo.destroy
    respond_to do |format|
      format.html { redirect_to loos_url, notice: 'Loo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loo
      @loo = Loo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loo_params
      params.require(:loo).permit(:lat, :lng, :name, :description, :open_hours, :closing_hours, :open_closing_note, :managed_by, :loo_type, :genders, :no_of_toilets, :no_of_bathrooms, :no_of_urinals, :paid, :location_name, :photo, :postal_code, :country, :locality, :administrative_area_level_1, :formatted_address, :category_id, attachments_attributes: [:file])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loos_helper.rb
module LoosHelper
  def display_loo_type(loo_type)
    loo_type =  "Western & Indian" if loo_type == "both"
    loo_type
  end
  
  def display_gender_type(gender_type)
    gender_type =  "Gents & Ladies" if gender_type == "all"
    gender_type
  end
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-xs-10">
        <%= f.input :name %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success btn-sm" %>
  </div>
  <br />
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 center-block" style="float: none;">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 style="margin: 0;">Editing Category</h1>
        </div>
        <div class="panel-body" style="padding-left: 50px;">
          <br />

          <%= render 'form' %>

          <%= link_to 'Back', categories_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 center-block" style="float: none;">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 style="margin: 0;">Categories</h2>
        </div>
        <div class="panel-body">
          <div class="row">
          <% @categories.each do |category| %>
            <div class="col-xs-6 col-md-4 text-center" style="margin-top: 30px;">
              <a href="<%= category_path(category) %>" class="thumbnail">
                <h2>
                  <%= category.name %> (<%= category.loos.size %>)
                </h2>
              </a>

              <% if user_signed_in? %>
              <small>
                <ul class="list-inline">
                  <li>
                    <%= link_to 'Show', category %>
                  </li>
                  <li>
                    <%= link_to 'Edit', edit_category_path(category) %>
                  </li>
                  <li>
                    <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </li>
                </ul>
              </small>
              <% end %>
            </div>
          <% end %>
          </div>
        </div>
      </div>

      <br>

      <%= link_to 'New Category', new_category_path, class: "btn btn-default" if user_signed_in? %>

    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 center-block" style="float: none;">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 style="margin: 0;">Add Category</h1>
        </div>
        <div class="panel-body" style="padding-left: 50px;">
          <br />

          <%= render 'form' %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 center-block" style="float: none;">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 style="margin: 0;"><%= @category.name %> (<%= @category.loos.size %>)</h2>
        </div>
        <div class="panel-body">
          <% if @category.loos.empty? %>
            <div class="alert alert-warning">
              No records found.
            </div>
          <% else %>
            <%= render @category.loos %>
          <% end %>
        </div>
      </div>
      <% if user_signed_in? %>
      <%= link_to 'Edit', edit_category_path(@category) %> |
      <%= link_to 'Back', categories_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 center-block" style="float: none;">
      <div class="jumbotron">
              <h1>The Loo Project</h1>
              <p class="lead"><u>The Loo Project - which helps you find clean loo around you by creating digital public toilet map. It Includes public toilets and shops, cafes, institutions which can let anyone use their facilities.</u> The Information is gathered by Municipal Corporations, Village Councils, Open Government Data, Partner organizations, and citizens. </p>
              <p class="lead">Mapping of data is just the beginning and there are many amazing things can be done once we have that data. 'Design Your Loo' initiative to bring people together to build affordable toilets and coming up with actionable data insights to build solutions for public toilets and sanitation.</p>
              <p class="lead">At <a href="http://eChai.in" target="_BLANK">eChai</a>, with Sweetly we are solving one challenging problem in Dangs Forest in a small way. And after Sweetly - once again we are super excited to work on The Loo Project which we believe will bring a great social impact some day.</p>
              <br>
              <div>For more information contact <br><br>Jatin Chaudhary, Co-Founder, eChai Ventures, <br><a href="mailto:jatin@eChai.in">jatin@eChai.in</a>, +91 87338 38470 <br><br> Kunal Chaudhary, Co-Founder, eChai Ventures,<br> <a href="mailto:kunal@eChai.in">kunal@eChai.in</a>, +91 99137 19765.</div>
        
            </div>  
      </div>
      
    </div>
  </div>

app/views/home/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-8 center-block" style="float: none; padding: 50px 0;">

      <div class="panel panel-default well">

        <div class="panel-body">

          <h1 style="margin-top: 0;">Find Nearby Loos</h1>

          <%= render 'shared/search_form' %>

          <hr />

          <p class="lead">The Loo Project - helps you find clean loo around you by creating digital public toilet map. It Includes public toilets and shops, cafes, institutions which can let anyone use their facilities.</p>

          <br />

          <% if user_signed_in? %>
          <p class="lead text-center">
            <a href="<%= new_loo_path %>" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-plus"></span> Share Loo location & info.</a>
          </p>
          <% else %>
            <h2>Get Started!</h2>
            <p class="lead">
              <a href="<%= new_user_session_path %>" style="text-decoration: underline;" >Sign in</a> or <a href="<%= new_user_registration_path %>" style="text-decoration: underline;" >Create an account</a> to share informations regarding loos.</p>
          <% end %>
        </div> <!-- panel-body -->

      </div> <!-- panel -->

    </div> <!-- col-md-8 -->

  </div> <!-- row -->

</div> <!-- container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/header' %>

  <%= yield %>


  <footer class="text-center text-muted" style="margin-top: 30px;">
    <ul class="list-inline">
      <li>
        &copy; TheLooProject 2015.
      </li>
    </ul>
  </footer>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheLooProject</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="devise">
  <%= render partial: 'shared/header' %>
  
  <div class="container">

    <div class="devise-content">
      <div class="row">
        <div class="col-md-6 center-block" style="float: none; padding: 20px;">
          <div class="panel panel-warning">
            <div class="panel-body devise-body" style="padding: 20px 30px;">
              <% if flash[:notice] %>
                <div class="alert alert-success">
                  <%= flash[:notice] %>
                </div>
              <% end %>
              <% if flash[:alert] %>
                <div class="alert alert-danger">
                  <%= flash[:alert] %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <footer class="footer text-center text-muted" style="margin-top: 30px;">
      <p>&copy; TheLooProject 2015.</p>
    </footer>

  </div>

</body>
</html>

app/views/loos/_actions.html.erb
<% if user_signed_in? %>
<ul class="list-inline">
  <li>
    <%= link_to "Edit", edit_loo_path(loo), class: "btn btn-default btn-sm" %>
  </li>
  <li>
    <%= link_to 'Destroy', loo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
  </li>
</ul>
<% end %>

app/views/loos/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 center-block" style="float: none;">

      <h1>Share loo location & Info.</h2>
      <hr />
      <div>
        <%= simple_form_for(@loo, defaults: { label: false }) do |f| %>
          <%= f.error_notification %>

          <div id="location_section" class="form-inputs">

            <div class="well">
              <div class="col-xs-10">
                <label>Enter location/area of Loo:</label>
                <%= f.input :location_name, placeholder: "Enter new location", input_html: { id: 'location_input', class: "location_input" } %>
                <span id="helpBlock" class="help-block">eg. Ahmedabad Airport, Ahmedabad, Gujarat, India.</span>
              </div>
              <div class="clearfix"></div>
            </div>

            <div class="well hide">
              <%= f.input :lat, input_html: { data: { geo: 'lat' } } %>
              <%= f.input :lng, input_html: { data: { geo: 'lng' } } %>
              <%= f.input :formatted_address, input_html: { data: { geo: 'formatted_address' } } %>
              <%= f.input :postal_code, input_html: { data: { geo: 'postal_code' } } %>
              <%= f.input :locality, input_html: { data: { geo: 'locality' } } %>
              <%= f.input :country, input_html: { data: { geo: 'country' } }, as: :string %>
              <%= f.input :administrative_area_level_1, input_html: { data: { geo: 'administrative_area_level_1' } } %>
            </div>

            <hr />

            <h3>Details:</h3>

            <div class="row">
              <div class="col-xs-8">
                <%= f.association :category, prompt: "Select Category" %>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-8">
                <%= f.file_field :photo %>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-xs-11">
                <%= f.input :name, placeholder: "Name: eg. Toilet at Central mall" %>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-xs-10">
                <%= f.input :description, placeholder: "Description", input_html: { rows: 5 } %>
              </div>
            </div>

            <hr />

            <h3>Open/Close status</h3>

            <div class="row">
              <div class="col-xs-4">
                <%= f.input :open_hours, placeholder: "Open hour: eg. 6:00 AM" %>
              </div>
              <div class="col-xs-4">
                <%= f.input :closing_hours, placeholder: "Closing hour: eg. 9:00 PM"  %>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-8">
                <%= f.input :open_closing_note, placeholder: "Open/Closing note: eg. Closed on saturday and sunday" %>
              </div>
            </div>

            <hr />
            <h3>Other details: </h3>

            <div class="row">
              <div class="col-xs-10">
                <%= f.input :managed_by, placeholder: "Managed by: eg. NASA Foundation" %>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-4">
                <%= f.input :loo_type, as: :select, collection: %w(western indian both), prompt: "Select Loo type" %>
              </div>
              <div class="col-xs-4">
                <%= f.input :genders, as: :select, collection: [["Gents", "gents"], ["Ladies", "ladies"], ["All", "all"]], prompt: "Select Gender Type" %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-4">
                <%= f.input :no_of_toilets, placeholder: "No. of toilets" %>
              </div>
              <div class="col-xs-4">
                <%= f.input :no_of_bathrooms, placeholder: "No. of bathrooms" %>
              </div>
              <div class="col-xs-4">
                <%= f.input :no_of_urinals, placeholder: "No. of urinals" %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-3">
                <%= f.input :paid, label: "Paid", as: :select, collection: [['No', 0], ['Yes', 1]], include_blank: false %>
              </div>
            </div>
          </div>

          <br />
          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-success" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/loos/_loo.html.erb
<hr />
        <div class="row">
          <div class="col-md-4">
            <a href="<%= loo_path(loo) %>">
              <%= image_tag loo.photo.url(:medium), class: "img-thumbnail" %>
            </a>
            <hr />
            <%= render :partial => 'loos/actions', locals: { loo: loo } %>
          </div>
          <div class="col-md-7">
            <h3 class="media-heading"><%= link_to loo.name, loo_path(loo) %></h3>
            <p><%= loo.location_name %></p>
            <%= render :partial => 'loos/summary', locals: { loo: loo } %>
          </div>
        </div>

app/views/loos/_summary.html.erb
<ul>
  <%= content_tag :li, "Loo Type: #{display_loo_type(loo.loo_type)}" unless loo.loo_type.blank? %>
  <%= content_tag :li, "Gender Type: #{display_gender_type(loo.genders)}" unless loo.genders.blank? %>
  <%= content_tag :li, "No of toilets: #{loo.no_of_toilets}" unless loo.no_of_toilets.blank? %>
  <%= content_tag :li, "No of bathrooms: #{loo.no_of_bathrooms}" unless loo.no_of_bathrooms.blank? %>
  <%= content_tag :li, "No of bathrooms: #{loo.no_of_urinals}" unless loo.no_of_urinals.blank? %>
  <%= content_tag :li, "Open hours: #{loo.open_hours}" unless loo.open_hours.blank? %>
  <%= content_tag :li, "Closing hours: #{loo.closing_hours}" unless loo.closing_hours.blank? %>
  <%= content_tag :li, loo.open_closing_note unless loo.open_closing_note.blank? %>
  <%= content_tag :li, loo.paid? ? "Paid" : "Free" %>
</ul>
<br />
<% unless loo.managed_by.blank? %>
<p>
  <strong>Managed by: </strong>
  <%= content_tag :h4, loo.managed_by %>
</p>
<% end %>

app/views/loos/edit.html.erb
<%= render 'form' %>

app/views/loos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 center-block" style="float: none;">

      <% if params[:q] %>
        <div class="well">
          <br />
          <%= render 'shared/search_form' %>
        </div>
      <% end %>

      <% unless @loos.empty? %>

      <% if params[:q] %>
        <h3>Search result (<%= @loos.size %>)</h3>
      <% else %>
        <h1>Listing Loos(<%= @loos.size %>)</h1>
      <% end %>
        <%= render @loos %>
      <% else %>
        <div class="alert alert-warning">
          <strong>No loos found.</strong>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/loos/new.html.erb
<%= render 'form' %>

app/views/loos/show.html.erb
<div class="container">
  <div class="row" style="margin-botton: 40px;">
    <div class="col-md-5">
      <%= image_tag @loo.photo.url(:medium), class: "img-thumbnail" %>
      <hr/>
      <%= render :partial => 'loos/actions', locals: { loo: @loo } %>
    </div>
    <div class="col-md-7">
      <h2><%= @loo.name %></h2>
      <h4><%= @loo.location_name %></h4>
      <%= content_tag :h5, "Postal code: #{@loo.postal_code}" unless @loo.postal_code.blank? %>

      <hr />

      <%= simple_format @loo.description %>
      
      <%= render :partial => 'loos/summary', locals: { loo: @loo } %>

      <hr />
      <p>
        <a href="javascript:void(0)" class="show_map" data-loo="<%= @loo.to_json %>"  style="text-decoration: underline;">View map</a>
      </p>
      <div style="width:500px; height: 400px;" id="map_canvas"></div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">The Loo Project</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="<%= categories_path %>"><span class="glyphicon glyphicon-list"></span> Categories</a></li>
        <li><a href="<%= loos_path %>"><span class="glyphicon glyphicon-list"></span> Broswe Loos</a></li>
        <li><a href="<%= new_loo_path %>"><span class="glyphicon glyphicon-plus"></span> Add Loo</a></li>
        <li><a href="<%= about_path %>">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a href="#">Welcome, <%= current_user.firstname %> <%= current_user.lastname %></a></li>
        <% else %>
        <li><a href="<%= new_user_registration_path %>">Sign up</a></li>
        <li><a href="<%= new_user_session_path %>">Sign in <span class="glyphicon glyphicon-log-in"></span></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_search_form.html.erb
<form action="<%= search_path %>" role="search">
  <div class="input-group input-group-lg">
    <input type="text" name="q" value="<%= params[:q] %>" class="form-control location_input" placeholder="Enter a location...">
    <span class="input-group-btn">
      <button type="submit" class="btn btn-danger" type="button">Find</button>
    </span>
  </div><!-- /input-group -->
  <span id="helpBlock" class="help-block">eg. Ahmedabad Airport, Ahmedabad, Gujarat, India.</span>
  <div id="location_section" class="form-inputs">
    <div class="well hide">
      <div><input data-geo="lat" value="<%= params[:loo][:lat] if params[:loo] && params[:loo] && params[:loo][:lat] %>" class="string optional form-control" type="text" name="loo[lat]" id="loo_lat"></div>
      <div><input data-geo="lng" value="<%= params[:loo][:lng] if params[:loo] && params[:loo][:lng] %>" class="string optional form-control" type="text" name="loo[lng]" id="loo_lng"></div>
      <div><input value="<%= params[:loo][:formatted_address] if params[:loo] && params[:loo][:formatted_address] %>" data-geo="formatted_address" class="text optional form-control" name="loo[formatted_address]" id="loo_formatted_address"/></div>
      <div><input value="<%= params[:loo][:postal_code] if params[:loo] && params[:loo][:postal_code]%>" data-geo="postal_code" class="string optional form-control" type="text" name="loo[postal_code]" id="loo_postal_code"></div>
      <div><input value="<%= params[:loo][:locality] if params[:loo] && params[:loo][:locality] %>" data-geo="locality" class="string optional form-control" type="text" name="loo[locality]" id="loo_locality"></div>
      <div><input value="<%= params[:loo][:country] if params[:loo] && params[:loo][:country] %>" data-geo="country" class="string optional form-control" type="text" name="loo[country]" id="loo_country"></div>
      <div><input value="<%= params[:loo][:administrative_area_level_1] if params[:loo] && params[:loo][:administrative_area_level_1] %>" data-geo="administrative_area_level_1" class="string optional form-control" type="text" name="loo[administrative_area_level_1]" id="loo_administrative_area_level_1"></div>
    </div>
  </div>
</form>